name: tanstart-barren-standalone-db

services:
  db:
    image: pgvector/pgvector:pg18
    env_file:
      - standalone-db.env
    ports:
      - "5440:5432"
    volumes:
      - postgres_data_tanstart_barren:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - tanstart-barren-development-network

volumes:
  postgres_data_tanstart_barren:

networks:
  tanstart-barren-development-network:
    external: true
